### PR TITLE
Happy tree friends

### LINKED ISSUE #6: Revamping the treemap
Algo así, algo bien :trollface:

http://www.nytimes.com/packages/html/newsgraphics/2011/0119-budget/

- [x] No traumarnos con los labels
- [x] Aprovechar el hover
- [x] O truncar títulos o eliminarlos

### PR DESCRIPTION
**Pull request by rodowi**
# Yet a work-in-progress

happy-tree-friends

Might fix #6

### CODE REVIEW

**Comment by rodowi** [comment]
screen shot 2015-12-04 at 8 57 27 pm

**Comment by netosw** [comment]
Muchísimo mejor esa solucion

On Friday, 4 December 2015, rodowi <notifications@github.com> wrote:

> [image: screen shot 2015-12-04 at 8 57 27 pm]
> <https://cloud.githubusercontent.com/assets/705860/11605602/d9f979b2-9ac9-11e5-920e-8624117a1c9b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opintel/clima/pull/7#issuecomment-162134511>.
>


-- 

Ernesto Galindo Rojo.

**Comment by rodowi** [comment]
work-in-progress

**Comment by rodowi** [comment]
Me gusta más #8!

**Pull request closed without merging**
